name: Terraform Deployment

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.7.0

    - name: Terraform Init
      run: terraform init
      working-directory: ./environments/dev

    - name: Terraform Plan
      run: terraform plan -var-file="terraform.tfvars"
      working-directory: ./environments/dev

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve -var-file="terraform.tfvars"
      working-directory: ./environments/dev
